name: botRunner

on:
  schedule:
    # This cron expression means "every 5th minute"
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # This speeds up subsequent runs

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Execute Python script
        run: python tradingbot.py
